spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:mysql://ec2-18-188-224-11.us-east-2.compute.amazonaws.com:3306/seckilling?characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root
    password: 515300
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: ec2-18-188-224-11.us-east-2.compute.amazonaws.com
    port: 6379

  mvc:
    view:
      prefix: /
      suffix: .html
  kafka:
    consumer:
      bootstrap-servers: ec2-18-188-224-11.us-east-2.compute.amazonaws.com:9092
      group-id: 0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ec2-18-188-224-11.us-east-2.compute.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8088
